spring.datasource.url=jdbc:postgresql://db:5432/rodritech_db
spring.datasource.username=admin
spring.datasource.password=secretpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect